src/IsThereAnybodyOutThere/Models/Actors/ClientRegistryActorRef.cs
using Akka.Actor;

namespace IsThereAnybodyOutThere.Models.Actors
{
    public class ClientRegistryActorRef : IActorRefWrapper
    {
        public ClientRegistryActorRef(IActorRef clientRegistry)
        {
            ActorRef = clientRegistry;
        }
        public IActorRef ActorRef { get; }
    }
}

src/IsThereAnybodyOutThere/Models/Actors/IActorRefWrapper.cs
using Akka.Actor;

namespace IsThereAnybodyOutThere.Models.Actors
{
    public interface IActorRefWrapper
    {
        IActorRef ActorRef { get; }
    }
}

src/IsThereAnybodyOutThere/Models/Clients/ClientListModel.cs
using System;
using System.Collections.Generic;

namespace IsThereAnybodyOutThere.Models.Clients
{
    public class ClientModel
    {
        public string Id { get; set; }
        public bool Connected { get; set; }

        public DateTime LastHeartbeatReceivedAtUtc { get; set; }
        public string MachineName { get; set; }
        public string Username { get; set; }
        public string ApplicationName { get; set; }
        public IEnumerable<Heartbeat> Heartbeats { get; set; }

        public class Heartbeat
        {
            public DateTime ReceivedAtUtc { get; set; }
            public Dictionary<string, object> Data { get; set; }
        }
    }
}

src/IsThereAnybodyOutThere/Models/Clients/CommonClientListViewModel.cs
using System.Collections.Generic;

namespace IsThereAnybodyOutThere.Models.Clients
{
    public class CommonClientListViewModel
    {
        public IEnumerable<ClientModel> Clients { get; set; }
    }
}

src/IsThereAnybodyOutThere/Controllers/ClientInstanceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Akka.Actor;
using IsThereAnybodyOutThere.Messages;
using IsThereAnybodyOutThere.Models.Actors;
using IsThereAnybodyOutThere.Models.Clients;
using Microsoft.AspNet.Mvc;

namespace IsThereAnybodyOutThere.Controllers
{
    public class ClientInstanceController : Controller
    {
        private IActorRef _clientRegistry;

        public ClientInstanceController(ClientRegistryActorRef clientRegistryActorRef)
        {
            _clientRegistry = clientRegistryActorRef.ActorRef;
        }

        [Route("client/{id}")]
        public async Task<IActionResult> Index(string id)
        {
            var clientModels = await _clientRegistry.Ask<IEnumerable<ClientModel>>(new GetClients());

            var client = clientModels.FirstOrDefault(f => f.Id == id);

            if (client == null)
            {
                return HttpNotFound();
            }

            return View(client);
        }
    }
}

src/IsThereAnybodyOutThere/Controllers/ClientsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection.Emit;
using System.Threading.Tasks;
using Akka.Actor;
using IsThereAnybodyOutThere.Messages;
using IsThereAnybodyOutThere.Models;
using IsThereAnybodyOutThere.Models.Actors;
using IsThereAnybodyOutThere.Models.Clients;
using Microsoft.AspNet.Mvc;

namespace IsThereAnybodyOutThere.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ClientRegistryActorRef _clientRegistry;

        public ClientsController(ClientRegistryActorRef clientRegistry)
        {
            _clientRegistry = clientRegistry;
        }

        [Route("")]
        public IActionResult ReditectToIndex()
        {
            return RedirectToAction("Index");
        }

        [Route("clients")]
        public async Task<IActionResult> Index()
        {
            var clients = await GetClients();

            return View(new CommonClientListViewModel { Clients = clients.OrderByDescending(o => o.LastHeartbeatReceivedAtUtc) });
        }

        private async Task<List<ClientModel>> GetClients(Func<ClientModel, bool> filter = null)
        {
            var clientModels = await _clientRegistry.ActorRef.Ask<List<ClientModel>>(new GetClients());

            if (filter != null)
            {
                clientModels = clientModels.Where(filter).ToList();
            }

            return clientModels;
        }

        [Route("clients/user/{username}")]
        public async Task<IActionResult> ByUser(string username)
        {
            ViewBag.Username = username;
            return View(new CommonClientListViewModel { Clients = await GetClients(model => model.Username == username) });

        }

        [Route("clients/application/{name}")]
        public async Task<IActionResult> ByApplication(string name)
        {
            ViewBag.ApplicationName = name;
            return View(new CommonClientListViewModel { Clients = await GetClients(model => model.ApplicationName == name) });

        }

        [Route("clients/machine/{name}")]
        public async Task<IActionResult> ByMachine(string name)
        {
            ViewBag.MachineName = name;
            return View(new CommonClientListViewModel { Clients = await GetClients(model => model.MachineName == name) });

        }
    }
}

src/IsThereAnybodyOutThere/Views/ClientInstance/Index.cshtml
@model IsThereAnybodyOutThere.Models.Clients.ClientModel

<h2>
    @Model.ApplicationName
</h2>
<div class="instance-info">
    <div class="pure-g">
        <div class="pure-u-2-24">Id</div>
        <div class="pure-u-4-24">@Model.Id</div>
    </div>
    <div class="pure-g">
        <div class="pure-u-2-24">Username</div>
        <div class="pure-u-4-24">@Model.Username</div>
    </div>
    <div class="pure-g">
        <div class="pure-u-2-24">Machine name</div>
        <div class="pure-u-4-24">@Model.MachineName</div>
    </div>
    <div class="pure-g">
        <div class="pure-u-2-24">Connected</div>
        <div class="pure-u-4-24">@Model.Connected</div>
    </div>
    <div class="pure-g">
        <div class="pure-u-2-24">Last heartbeat</div>
        <div class="pure-u-4-24">@Model.LastHeartbeatReceivedAtUtc.ToLocalTime()</div>
    </div>
</div>
<h3>
    Latest heartbeats
</h3>
<div class="instance-hearbeats">
    <div class="pure-g">
        <div class="pure-u-2-24">Heartbeat</div>
        <div class="pure-u-4-24"></div>
    </div>

    @foreach (var hb in Model.Heartbeats)
    {
        <div class="pure-g">
            <div class="pure-u-2-24">@hb.ReceivedAtUtc</div>
            <div class="pure-u-4-24"></div>
        </div>
    }

</div>

src/IsThereAnybodyOutThere/Views/Clients/ByApplication.cshtml
@model IsThereAnybodyOutThere.Models.Clients.CommonClientListViewModel

<h2>
    @ViewBag.ApplicationName
</h2>
<p class="info">@Model.Clients.Count(c => c.Connected) instances of '@ViewBag.ApplicationName' are connected</p>
@Html.Partial("_CommonClientListPartial", Model.Clients)

src/IsThereAnybodyOutThere/Views/Clients/ByMachine.cshtml
@model IsThereAnybodyOutThere.Models.Clients.CommonClientListViewModel

<h2>
    @ViewBag.MachineName
</h2>
<p class="info">'@ViewBag.MachineName' has @Model.Clients.Count(c => c.Connected) instances connected</p>
@Html.Partial("_CommonClientListPartial", Model.Clients)

src/IsThereAnybodyOutThere/Views/Clients/ByUser.cshtml
@model IsThereAnybodyOutThere.Models.Clients.CommonClientListViewModel

<h2>
    @ViewBag.Username
</h2>
<p class="info">'@ViewBag.Username' has @Model.Clients.Count(c => c.Connected) instances connected</p>
@Html.Partial("_CommonClientListPartial", Model.Clients)

src/IsThereAnybodyOutThere/Views/Clients/Index.cshtml
@model IsThereAnybodyOutThere.Models.Clients.CommonClientListViewModel

<h2>
    All registered clients
</h2>
@Html.Partial("_CommonClientListPartial", Model.Clients)

src/IsThereAnybodyOutThere/Views/Clients/_ClientListPartial.cshtml
@model IEnumerable<IsThereAnybodyOutThere.Models.Clients.ClientModel>

<div>
    <div class="pure-g client-list-header">
        <div class="pure-u-4-24">Id</div>
        <div class="pure-u-4-24">Application name</div>
        <div class="pure-u-4-24">Machine name</div>
        <div class="pure-u-4-24">Username</div>
        <div class="pure-u-4-24">Connected</div>
        <div class="pure-u-4-24">Last heartbeat</div>
    </div>
    @foreach (var client in Model)
    {
        <div class="pure-g client-list-row">
            <div class="pure-u-4-24"><a asp-action="Index" asp-controller="ClientInstance" asp-route-id="@client.Id">@client.Id</a></div>
            <div class="pure-u-4-24"><a asp-action="ByApplication" asp-controller="Clients" asp-route-name="@client.ApplicationName">@client.ApplicationName</a></div>
            <div class="pure-u-4-24"><a asp-action="ByMachine" asp-controller="Clients" asp-route-name="@client.MachineName">@client.MachineName</a></div>
            <div class="pure-u-4-24"><a asp-action="ByUser" asp-controller="Clients" asp-route-username="@client.Username">@client.Username</a></div>
            <div class="pure-u-4-24">@client.Connected</div>
            <div class="pure-u-4-24">@client.LastHeartbeatReceivedAtUtc.ToLocalTime()</div>
        </div>
    }
</div>

src/IsThereAnybodyOutThere/Views/Clients/_CommonClientListPartial.cshtml
@model IEnumerable<IsThereAnybodyOutThere.Models.Clients.ClientModel>

@{
    var connected = Model.Where(c => c.Connected).ToList();
    var disconnected = Model.Where(c => !c.Connected).ToList();
}
<div class="connected">
    <h3>
        Connected (@connected.Count())
    </h3>
    @Html.Partial("_ClientListPartial", connected)
</div>

<div class="disconnected">
    <h3>
        Disconnected (@disconnected.Count())
    </h3>
    <p class="info">Client instances that were online at some point</p>
    @Html.Partial("_ClientListPartial", disconnected)
</div>

src/IsThereAnybodyOutThere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link href="~/css/styles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="header">
        <h1>
            Is there anybody out there?
        </h1>
        <a asp-action="Index" asp-controller="Clients">All clients</a>
    </div>
<div class="content">
    @RenderBody()
</div>
<div>
    <br />
    <br />
</div>
</body>
</html>